# Generated by Django 5.1.5 on 2025-02-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
