# Generated by Django 5.1.5 on <current_date>
# account/migrations/0004_auto_20250224_1821.py


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_first_name_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]