# Generated by Django 5.1.5 on 2025-02-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20250301_0000'),
        ('accounts', '0005_update_email_field'),
    ]

    operations = [
    ]
