services:
# web:
  # container_name: jireh_web
  web:
    build: .
    command: python /backend/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/backend
    ports:
    - 8000:8000
    depends_on:
    - db
    environment:
    - DJANGO_SECRET_KEY=django-insecure-71%@ogk-j=d(x=rl^fry9yvwpy)ix&5k5@u8cec59a@1j+$4r!
    - DJANGO_DEBUG=True
    - ROTATE_REFRESH_TOKENS=False
    - BLACKLIST_AFTER_ROTATION=False
    - UPDATE_LAST_LOGIN=False
  db:
    image: postgres:17
    volumes:
    - jdb_postgres_data:/var/lib/postgresql/data/
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  jdb_postgres_data: