# Generated by Django 5.1.5 on 2025-02-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='unit_of_measure',
            field=models.CharField(blank=True, choices=[('pieces', 'Pieces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('L', 'Liters'), ('ml', 'Milliliters'), ('m', 'Meters'), ('box', 'Box'), ('pack', 'Pack')], max_length=10, null=True),
        ),
    ]
