# Generated by Django 5.1.5 on 2025-02-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('items', '0002_items_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='business_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branches'),
        ),
    ]
