# Generated by Django 5.1.5 on 2025-02-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_registration_number'),
        ('items', '0003_items_business_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
    ]
