# Generated by Django 5.1.5 on 2025-02-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branches')),
            ],
            options={
                'indexes': [models.Index(fields=['business_branch', 'is_active'], name='idx_category_business_branch')],
            },
        ),
    ]
