# Generated by Django 5.1.5 on 2025-02-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categories',
            name='idx_category_business_branch',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='business_branch',
        ),
        migrations.AddField(
            model_name='categories',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.business'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['business', 'is_active'], name='idx_category_business_branch'),
        ),
    ]
