# Generated by Django 5.1.5 on 2025-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_categories_idx_category_business_branch_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categories',
            name='idx_category_business_branch',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='business',
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['is_active'], name='idx_category'),
        ),
    ]
