# Generated by Django 5.1.5 on 2025-02-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_registration_number'),
        ('categories', '0003_remove_categories_idx_category_business_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['business', 'is_active'], name='idx_category_business'),
        ),
    ]
