# Generated by Django 5.1.5 on 2025-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='name',
            field=models.CharField(default='Expense', max_length=100),
        ),
        migrations.AddField(
            model_name='expenses',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='recurring_frequency',
            field=models.CharField(
                blank=True, 
                choices=[
                    ('once', 'One Time'),
                    ('daily', 'Daily'), 
                    ('weekly', 'Weekly'), 
                    ('monthly', 'Monthly'), 
                    ('quarterly', 'Quarterly'), 
                    ('halfYearly', 'Half Yearly'), 
                    ('yearly', 'Yearly')
                ], 
                max_length=20, 
                null=True
            ),
        ),
    ]