# Generated by Django 5.1.5 on 2025-02-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_registration_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterField(
            model_name='business',
            name='address_city',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='business',
            name='address_street',
            field=models.TextField(default='Unknown'),
        ),
    ]
